// <auto-generated />
namespace AplicatieSalariati.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changedfromdatetostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedfromdatetostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201906021339152_Changed from date to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
